spring:
  profiles: production
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect